# Generated by Django 3.0.6 on 2020-05-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=10)),
                ('klass', models.CharField(max_length=10)),
                ('stream', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('level', models.CharField(choices=[('Alevel', 'Alevel'), ('Olevel', 'Olevel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sir_name', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=8)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passports')),
                ('klass', models.CharField(choices=[('S.1', 'S.1'), ('S.2', 'S.2'), ('S.3', 'S.3'), ('S.4', 'S.4'), ('S.5', 'S.5'), ('S.6', 'S.6')], max_length=5)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S')], max_length=10)),
                ('house', models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('France', 'France'), ('Japan', 'Japan'), ('Nigeria', 'Nigeria')], max_length=10, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=6)),
                ('alevel', models.BooleanField(default=False)),
                ('olevel', models.BooleanField(default=False)),
                ('olevel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('alevel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_compulsary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('marklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportcards.MarkList')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportcards.Paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportcards.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportcards.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportcards.MarkList')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportcards.Student')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportcards.Subject'),
        ),
        migrations.CreateModel(
            name='MarkListSetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_papers', models.BooleanField(default=False)),
                ('num_exams', models.IntegerField()),
                ('marklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportcards.MarkList')),
            ],
        ),
    ]
